version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dev-dynamo
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data
    networks:
      - my_network
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./dynamodb_data"]

volumes:
  redis_data:
  dynamodb_data:

networks:
  my_network: